version: '3.3'

services:
  webserver:
    image: erseco/alpine-php-webserver
    container_name: php
    ports:
      - 8080:8080
    volumes:
      - ./php:/var/www/html
    restart: unless-stopped
    networks:
      - tunnel

networks:
  tunnel:
    external: true
